Repository milieuinfo/webcomponent-vl-ui-search, pull requests merged in 2020-06, with the labels that each got.

#14 Introductie vl-ui-demo en ESlint
  .eslintrc.json
  CODEOWNERS
  demo/demo.css
  demo/demo.css.map
  demo/demo.js
  demo/performance.html
  demo/vl-search.html
  index.js
  package-lock.json
  package.json
  performance/README.md
  performance/config/budget.json
  performance/config/config-chrome.json
  performance/config/config-firefox.json
  performance/scripts/preScript.js
  src/index.js
  src/style.css
  src/style.css.map
  src/vl-search.js
  test/e2e/components/vl-search.js
  test/e2e/pages/vl-search.page.js
  test/e2e/search.test.js
  test/unit/vl-search.test.html
Labels: chore

#15 Fix eslint errors
  .vscode/launch.json
  package-lock.json
Labels: bugfix

#19 Introductie nieuw Vlaanderen icon font
  package-lock.json
  package.json
  src/style.css
Labels: bug

#13 Introductie ondersteuning voor input slot elementen
  demo/vl-search.html
  dist/style.css
  dist/style.css.map
  dist/style.scss
  dist/vl-search.js
  dist/vl-search.min.js
  dist/vl-search.src.js
  package-lock.json
  package.json
  src/style.css
  src/style.css.map
  src/style.scss
  src/vl-search.js
  test/e2e/pages/vl-search.page.js
  test/e2e/search.test.js
  test/unit/vl-search.test.html
Labels: enhancement

#23 Update dependencies vl-ui-input-field en vl-ui-select
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: chore

#22 Introductie style width variable om breedte van inline variant te kunnen bepalen
  dist/style.css
  dist/style.css.map
  dist/style.scss
  dist/vl-search.js
  dist/vl-search.min.js
  dist/vl-search.src.js
  index.js
  package.json
  src/style.css
  src/style.css.map
  src/style.scss
  src/vl-search.js
  test/unit/vl-search.test.html
Labels: enhancement

#24 Deduplicatie NPM run scripts
  package-lock.json
  package.json
Labels: chore
